name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: docker login -u $DOCKER_USER --password $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build --label version=14 --file Dockerfile --tag ${{secrets.DOCKER_USER}}/postgres:14 --tag ${{secrets.DOCKER_USER}}/postgres:latest .
    - name: Docker Push
      run: | 
          docker push ${{secrets.DOCKER_USER}}/postgres:14
          docker push ${{secrets.DOCKER_USER}}/postgres:latest
